### ISSUE TITLE
Introduces 3 security issues

### ISSUE THREAD

**Issue by bbaassssiiee** [mamercad/ansible-icinga2-server#3]
1. disables firewall.
2. disables selinux.
3. unencrypted password in plaintext file.

**Comment by mamercad** [comment]
1. fixed
2. http://docs.icinga.org/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/selinux
3. put in vars/main.yml (still in a plaintext file though, what do you propose?)

**Comment by bbaassssiiee** [comment]
Ansible has ansible-vault for data at rest so consumers of this role can use that, but what is worrying is that you write the password to /root/.my.cnf 
while convenient it will not pass all auditors.
