### ISSUE TITLE
Add icingaweb admin user not idempotent.

### ISSUE THREAD

**Issue by bbaassssiiee** [mamercad/ansible-icinga2-server#4]
TASK [mamercad.icinga2-server : Add icingaweb admin user] **********************
fatal: [data1]: FAILED! => {"changed": true, "cmd": ["mysql", "--user=icingaweb2", "--password=icingaweb2", "icingaweb2", "--execute=INSERT INTO icingaweb_user (name, active, password_hash) VALUES ('icingaadmin', 1, '$1$gPGVfVUf$LA6B2Prrt.PzHLXrHvIjb1');"], "delta": "0:00:00.008734", "end": "2016-09-03 08:29:06.628216", "failed": true, "rc": 1, "start": "2016-09-03 08:29:06.619482", "stderr": "ERROR 1062 (23000) at line 1: Duplicate entry 'icingaadmin' for key 'PRIMARY'", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by mamercad** [comment]
should be taken care of in my latest commit
